Refactored build test to be run by travis without checkout

diff --git a/git/pre-push b/git/pre-push
--- a/git/pre-push
+++ b/git/pre-push
@@ -1,3 +1,80 @@
 #!/usr/bin/env bash
 
-bin/build-dev-leave-prod
+###
+# Helper functions
+##
+function info () {
+	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
+}
+
+function success() {
+	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
+}
+
+function warn() {
+  printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
+}
+
+function sub_warn() {
+  printf "\r\033[2K  [\033[0;31mWARN\033[0m] \t%s\n" "$1"
+}
+
+function stash_pop() {
+	# Puts back the stuff that wasn't committed
+	info "Git stashing: Putting back temporarily stashed files"
+	git stash pop -q
+}
+
+function stash_push() {
+    info "Git stashing: Stashing non-committed files temporarily"
+    if git stash save -u -q; then
+        success "Git stashing: All non-committed files have been temporarily stashed"
+    else
+        warn "Git stashing: An error occurred trying to stash non-relevant files, please check for any merge conflicts"
+        exit 1
+    fi
+}
+
+function cleanup() {
+    # Starts the jekyll serve in the background since
+    # `jekyll build`'s JEKYLL_ENV can't be overridden
+    # For more details, see https://github.com/jekyll/jekyll/issues/6397
+
+    # PID of the jekyll serve process is $1
+    jekyll_pid=$1
+
+    # Kill the process
+    info "Cleanup: Killing the jekyll PID: $jekyll_pid"
+    kill -INT $jekyll_pid
+    success "Cleanup: Killed the jekyll PID: $jekyll_pid"
+
+    # Unstash everything
+    stash_pop
+
+    # Remove the build artifacts
+    rm -rf _site/*
+
+    # Rebuild everything for production
+    if jekyll build &> /dev/null ; then
+        success "Build: Jekyll build step was successful"
+    else
+        warn "Build: Jekyll build step failed"
+        exit 1
+    fi
+}
+
+# Makes sure that the script doesn't run on stuff outside of the committed repo
+stash_push
+
+if bin/build-dev-leave-prod ; then
+    cleanup $jekyll_pid
+else
+    cleanup $jekyll_pid
+    exit 1
+fi
+
+
+
+
+
+
