Added in hack to workaround jekyll build being shitty

diff --git a/git/pre-push b/git/pre-push
--- a/git/pre-push
+++ b/git/pre-push
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+CURRENT_BUILD_TIME_MAX=20
+
 ###
 # Helper functions
 ##
@@ -7,30 +9,58 @@ function info () {
 	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
 }
 
-function success () {
+function success() {
 	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
 }
 
-function warn () {
+function warn() {
   printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
 }
 
-function sub_warn () {
+function sub_warn() {
   printf "\r\033[2K  [\033[0;31mWARN\033[0m] \t%s\n" "$1"
 }
 
-function stash_pop () {
+function stash_pop() {
 	# Puts back the stuff that wasn't committed
 	info "Git stashing: Putting back temporarily stashed files"
 	git stash pop -q
 }
 
-function stash_push () {
+function stash_push() {
     info "Git stashing: Stashing non-committed files temporarily"
     if git stash save -u -q; then
         success "Git stashing: All non-committed files have been temporarily stashed"
     else
         warn "Git stashing: An error occurred trying to stash non-relevant files, please check for any merge conflicts"
+        exit 1
+    fi
+}
+
+function cleanup() {
+    # Starts the jekyll serve in the background since
+    # `jekyll build`'s JEKYLL_ENV can't be overridden
+    # For more details, see https://github.com/jekyll/jekyll/issues/6397
+
+    # PID of the jekyll serve process is $1
+    jekyll_pid=$1
+
+    # Kill the process
+    info "Cleanup: Killing the jekyll PID: $jekyll_pid"
+    kill -INT $jekyll_pid
+    info "Cleanup: Killed the jekyll PID: $jekyll_pid"
+
+    # Unstash everything
+    stash_pop
+
+    # Remove the build artifacts
+    rm -rf _site/*
+
+    # Rebuild everything for production
+    if jekyll build &> /dev/null ; then
+        success "Build: Jekyll build step was successful"
+    else
+        warn "Build: Jekyll build step failed"
         exit 1
     fi
 }
@@ -41,21 +71,37 @@ function stash_push () {
 # Makes sure that the script doesn't run on stuff outside of the committed repo
 stash_push
 
-# Generates the static site
-if jekyll build &> /dev/null ; then
-    success "Build: Jekyll build step was successful"
-else
-    warn "Build: Jekyll build step failed"
-    stash_pop
-    exit 1
-fi
+# Generates the development static site
+# We require this hack since we can't build
+# with `JEKYLL_ENV=development jekyll build`
+# since Jekyll is retarded.
+info "Serve: Starting a Jekyll server in the background"
+bundle exec jekyll serve &
+jekyll_pid=$!
+info "Serve: Jekyll server has started in the background"
+
+# Sleeps for a bit while the site is building.
+# NOTE: This value will need to be changed
+# to be greater than the current required
+# build time
+
+sleep $CURRENT_BUILD_TIME_MAX
 
 # Runs through the test suite
 if bin/test ; then
     success "Test: All tests passed correctly"
-    stash_pop
+    cleanup $jekyll_pid
 else
     warn "Test: Some tests failed to pass"
-    stash_pop
+    cleanup $jekyll_pid
     exit 1
 fi
+
+
+
+
+
+
+
+
+
